# fly.toml app configuration file generated for driving-license-exams on 2025-06-23T12:42:47+04:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'driving-license-exams'
primary_region = 'fra'

[build]
  [build.args]
    GO_VERSION = '1.24.4'

[env]
  PORT = '8080'

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
